var data = [{
        name: "陈晓芳",
        sex: true,
        age: 16,
        phone: 15093105620,
        fav: ["画画", "睡觉"],
        height: 177,
        des: "生活还是朋友都是越简单越好",
    }, {
        name: "王苗迪",
        sex: false,
        age: 10,
        phone: 17630859124,
        fav: ["吃饭", "睡觉"],
        height: 175,
        des: "简简单单",
    }, {
        name: "魏一帆",
        sex: false,
        age: 12,
        phone: 15690737051,
        fav: ["美食", "运动"],
        height: 182,
        des: "说不出话",
    }, {
        name: "赵元凯",
        sex: false,
        age: 19,
        phone: 17319740718,
        fav: ["动漫", "睡觉"],
        height: 178,
        des: "知世就是力量",
    }, {
        name: "刘畅",
        sex: true,
        age: 20,
        phone: 18939244176,
        fav: ["小说", "睡觉"],
        height: 170,
        des: "明天有是新的一天",
    }, {
        name: "武福涛",
        sex: false,
        age: 13,
        phone: 16650787890,
        fav: ["吃饭", "睡觉"],
        height: 110,
        des: "不知所措",
    }, {
        name: "张宇亮",
        sex: false,
        age: 1,
        phone: 17538707925,
        fav: ["阿巴阿巴", "呜呼"],
        height: 174,
        des: "想不出来",
    }, {
        name: "肖雪雨",
        sex: false,
        age: 22,
        phone: 13525861483,
        fav: ["动漫", "睡觉"],
        height: 182,
        des: "展示想不出来",
    }, {
        name: "刘政",
        sex: false,
        age: 18,
        phone: 15738379727,
        fav: ["逆水寒", "睡觉"],
        height: 175,
        des: "简单",
    }, {
        name: "刘力源",
        sex: false,
        age: 21,
        phone: 13673590532,
        fav: ["干饭"],
        height: 160,
        des: "爱情哪有干饭香",
    }, {
        name: "张孟秋",
        sex: true,
        age: 20,
        phone: 13383769059,
        fav: ["吃", "睡"],
        height: "还在长个",
        des: "每天欧气",
    }, {
        name: "宋昂",
        sex: true,
        age: 23,
        phone: 15729237225,
        fav: ["唱", "跳", "rap", "篮球"],
        height: 172,
        des: "你kin你擦",
    }, {
        name: "郭辰露",
        sex: false,
        age: 31,
        phone: 19939972140,
        fav: ["游戏", "动漫"],
        height: 173,
        des: "等天黑",
    }, {
        name: "胡金龙",
        sex: false,
        age: 19,
        phone: 18539902653,
        fav: ["干饭", "游戏"],
        height: 178,
        des: "别回头也别将就",
    }, {
        name: "石博",
        sex: false,
        age: 6,
        phone: 18839235794,
        fav: ["游戏", "睡觉", "篮球"],
        height: 175,
        des: "山不向我来，我便向山去",
    }, {
        name: "王文龙",
        sex: false,
        age: 20,
        phone: 15093553585,
        fav: ["打游戏", "睡觉", "小说"],
        height: 170,
        des: "离别是重逢的开始,这次的离别是为了下次的相遇",
    }, {
        name: "杨通",
        sex: false,
        age: 23,
        phone: 15896944209,
        fav: ["旅游", "听音乐", '看小说'],
        height: 170,
        des: "何以解愁，唯有暴富",
    }, {
        name: "陈新宇",
        sex: false,
        age: 21,
        phone: 17634485691,
        fav: ["数码", "摄影"],
        height: 175,
        des: "来颗华子",
    }, {
        name: "张家祥",
        sex: false,
        age: 20,
        phone: 15890015374,
        fav: ["美食", "运动"],
        height: 180,
        des: "美滋滋",
    }, {
        name: "赵修淼",
        sex: false,
        age: 19,
        phone: 13203783712,
        fav: ["唱", "跳", "rap", "篮球"],
        height: 170,
        des: "大意了，没有闪",
    }, {
        name: "常红雷",
        sex: false,
        age: 21,
        phone: 13673309524,
        fav: ["干饭", "睡觉", "游玩", "各项运动"],
        height: 175,
        des: "世界这么大,我想去睡觉",
    }, {
        name: "梅永康",
        sex: false,
        age: 18,
        phone: 15294918488,
        fav: ["吃饭", "睡觉"],
        height: 175,
        des: "1",
    }, {
        name: "王松威",
        sex: false,
        phone: 13523475779,
        fav: ["动漫", "小说"],
        height: 178,
        des: "好好学习, 天天向上"
    }, {
        name: "张涛",
        sex: false,
        age: 15,
        phone: 15138933473,
        fav: ["音乐", "追剧"],
        height: 175,
        des: "奥利给! 干就完事啦!",
    }, {
        name: "张浩哲",
        sex: false,
        age: 19,
        phone: 18595449124,
        fav: ["DOTA", "羽毛球"],
        height: 175,
        des: "这波随便打",
    }, {
        name: "王润达",
        sex: false,
        age: 22,
        phone: 18530980904,
        fav: ["跑步", "网游"],
        height: 186,
        des: "今朝有酒今朝醉",
    }, {
        name: "罗艳龙",
        sex: false,
        age: 20,
        phone: 18530754684,
        fav: ["看小说", "打游戏"],
        height: 177,
        des: "山巅自相逢",
    }, {
        name: "从超超",
        sex: false,
        age: 20,
        phone: 15703810321,
        fav: ["游玩", "科幻电影"],
        height: 173,
        des: "尽人事听天命",
    }, {
        name: "胡俊",
        sex: false,
        age: 16,
        phone: 13782910919,
        fav: ["美食", "睡觉"],
        height: 177,
        des: "好开心",
    }, {
        name: "张欣梦",
        sex: true,
        age: 20,
        phone: 15565553158,
        fav: ["旅游", "拍照"],
        height: 170,
        des: "description",
    }, {
        name: "孙世源",
        sex: false,
        age: 19,
        phone: 15515586297,
        fav: ["逛街", "小吃", "追剧", "游戏"],
        height: 173,
        des: "非淡泊无以明志，非宁静无以致远。",
    }, {
        name: "孙天利",
        sex: false,
        age: 20,
        phone: 15093105620,
        fav: ["王者", "睡觉", "听歌"],
        height: 175,
        des: "开心最重要",
    }, {
        name: "梁申涛",
        sex: false,
        age: 18,
        phone: 13839471652,
        fav: ["干饭人,干饭魂,干饭都是人上人 ", "睡觉", "精通各种饭局", "精通一切"],
        height: 178,
        des: "生活除了干饭就是干饭,世界那么大,我想去看看各种各样的人",
    }, {
        name: "张靖阳",
        sex: false,
        age: 21,
        phone: 13323971669,
        fav: ["吃饭", "睡觉"],
        height: 171,
        des: "不知道写啥,就这样吧",
    }, {
        name: "张浩林",
        sex: false,
        age: 0.1,
        phone: 13137503756,
        fav: ["黑科技"],
        height: 120,
        des: "Love Life",
    }, {
        name: "曾庆贺",
        sex: false,
        age: 3,
        phone: 18317200860,
        fav: ["盗墓笔记", "qq飞车"],
        height: 170,
        des: "冲冲冲",

    }, {
        name: "邢朝令",
        sex: false,
        age: 28,
        phone: 17513542673,
        fav: [""],
        height: 178,
        des: "",
    }, {
        name: "朱家臣",
        sex: true,
        age: 18,
        phone: 11111111111,
        fav: ["吃饭", "睡觉", "哲学♂"],
        height: 178,
        des: "迎着光上吧！！",
    }, {
        name: "尚帅宏",
        sex: false,
        age: 20,
        phone: 18530621183,
        fav: ["枪械", "古装剧"],
        height: 195,
        des: "拂清风 饮烈酒 一朝醉 亿思愁",
    }, {
        name: "王卡",
        sex: true,
        age: 20,
        phone: 11111111111,
        fav: ["看书", "看剧"],
        height: 170,
        des: "好好学习",
    },
    {
        name: "王斌",
        sex: false,
        age: 21,
        phone: 11111111111,
        fav: ["打篮球", "看动漫", "唱歌"],
        height: 190,
        des: "好好学习",
    },
    {
        name: "陈家鑫",
        sex: false,
        age: 20,
        phone: 11111111111,
        fav: ["看书", "看剧"],
        height: 170,
        des: "好好学习",
    }, {
        name: "郭旭",
        sex: false,
        age: 0,
        phone: 13526468761,
        fav: ["装逼"],
        height: 1,
        des: "装B",
    },
];